require_relative '../lib/helper'

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

def simple
  triangle = Enumerator.new do |n|
    pos = 2
    sum = 1

    loop do
      n << sum

      sum += pos
      pos += 1
    end
  end

  triangle.each do |t|
    divs = divisors(t)
    return t if divs.length >= 500
  end
end

run(12) do
  simple
end
